version: "3.7"

# Database + Webserver (under http, for testing setup on localhost:80)
#
# docker-compose -f docker-compose.dev.yml up -d
#

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
  web:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEFAULT_DATABASE_HOSTNAME=postgres
      - DEFAULT_DATABASE_PORT=5432
    ports:
      - 80:8000
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./media:/www/data/images
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app
  #   networks:
  #     - network

volumes:
  postgres_data:
