"""create Album table

Revision ID: b00ff4639599
Revises: 031cc5641c5e
Create Date: 2023-03-14 20:46:54.490020

"""
from alembic import op
import sqlalchemy as sa
from app.models import Album
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "b00ff4639599"
down_revision = "031cc5641c5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type_", sa.String(length=10), nullable=False),
        sa.Column("catalog_id", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=30), nullable=False),
        sa.Column(
            "format",
            sqlalchemy_utils.types.choice.ChoiceType(Album.FORMAT),
            nullable=False,
        ),
        sa.Column("limitation", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("albums")
    # ### end Alembic commands ###
