"""create  table

Revision ID: a3d16d2075dc
Revises: 7e54a9922282
Create Date: 2023-03-15 22:53:07.752445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3d16d2075dc"
down_revision = "7e54a9922282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "songs", sa.Column("sound_time", sa.Float(precision=3), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songs", "sound_time")
    # ### end Alembic commands ###
