"""create  table

Revision ID: 05f5d5e4d77f
Revises: 97a73ac8dca1
Create Date: 2023-03-18 12:21:28.495482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05f5d5e4d77f"
down_revision = "97a73ac8dca1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "albums", "commentary", existing_type=sa.VARCHAR(length=300), nullable=True
    )
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "albums", "commentary", existing_type=sa.VARCHAR(length=300), nullable=False
    )
    # ### end Alembic commands ###
