"""create  table

Revision ID: 69f72b053cc7
Revises: dca4b268b906
Create Date: 2023-03-15 23:58:45.165868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69f72b053cc7"
down_revision = "dca4b268b906"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album_pictures",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("path", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "associations_album_picture",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("album_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("picture_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["picture_id"],
            ["album_pictures.id"],
        ),
        sa.PrimaryKeyConstraint("id", "album_id", "picture_id"),
    )
    op.add_column(
        "association_band_pictures",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
    )
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("association_band_pictures", "id")
    op.drop_table("associations_album_picture")
    op.drop_table("album_pictures")
    # ### end Alembic commands ###
