"""create  table

Revision ID: 97a73ac8dca1
Revises: 0f6e923fed53
Create Date: 2023-03-17 20:08:30.595498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97a73ac8dca1"
down_revision = "0f6e923fed53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bands", "commentary", existing_type=sa.VARCHAR(length=300), nullable=True
    )
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "bands", "commentary", existing_type=sa.VARCHAR(length=300), nullable=False
    )
    # ### end Alembic commands ###
