"""create  table

Revision ID: 64941cdbfb4e
Revises: c59c0eb5765d
Create Date: 2023-03-17 16:34:38.629683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64941cdbfb4e"
down_revision = "c59c0eb5765d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
