"""create  table

Revision ID: 713a7c440354
Revises: 9deafc64256b
Create Date: 2023-03-18 21:08:07.232272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "713a7c440354"
down_revision = "9deafc64256b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "album_pictures",
        "path",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "album_pictures",
        "path",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=60),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
