"""create band table

Revision ID: 031cc5641c5e
Revises: 57fdad9e0fdc
Create Date: 2023-03-14 18:48:11.789240

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models import Band

# revision identifiers, used by Alembic.
revision = "031cc5641c5e"
down_revision = "57fdad9e0fdc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bands",
        sa.Column(
            "status",
            sqlalchemy_utils.types.choice.ChoiceType(Band.STATUS),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bands", "status")
    # ### end Alembic commands ###
