"""create  table

Revision ID: 584cf4a8f251
Revises: 713a7c440354
Create Date: 2023-03-18 22:04:22.389290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "584cf4a8f251"
down_revision = "713a7c440354"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("albums", sa.Column("release_date", sa.DateTime(), nullable=False))
    op.add_column("albums", sa.Column("version_desc", sa.String(), nullable=False))
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songs",
        "sound_time",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("albums", "version_desc")
    op.drop_column("albums", "release_date")
    # ### end Alembic commands ###
