"""create  table

Revision ID: 7e54a9922282
Revises: 0edf899cdf6d
Create Date: 2023-03-15 22:07:29.785510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e54a9922282"
down_revision = "0edf899cdf6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("genre", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association_table_band_genres",
        sa.Column("band_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("genre_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["band_id"],
            ["bands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.PrimaryKeyConstraint("band_id", "genre_id"),
    )
    op.add_column(
        "albums", sa.Column("band_id", sa.UUID(as_uuid=False), nullable=False)
    )
    op.create_foreign_key(None, "albums", "bands", ["band_id"], ["id"])
    op.add_column(
        "bands", sa.Column("description", sa.String(length=800), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bands", "description")
    op.drop_constraint(None, "albums", type_="foreignkey")
    op.drop_column("albums", "band_id")
    op.drop_table("association_table_band_genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
